[package]
name = "leyaly-project"
version = "0.1.0"
edition = "2024"

[dependencies]

approx = "0.5.1"
crossterm = "0.28.1"
ratatui = "0.29.0"
rustfft = "6.2.0"
rand = "0.9.0"
cpal = "0.15.3"
ringbuffer = "0.15.0"
